
# nodeのstable版を公式ページから確認し、DockerHubからalpineベースのものを指定
FROM node:16.13.2-alpine

# docker-compose.ymlからWORKDIRの値を受け取る
ARG WORKDIR

# コンテナのホームディレクトリを設定する
ENV HOME=/${WORKDIR}

RUN mkdir -p /myapp

# コマンド実行する作業ディレクトリの設定する
WORKDIR /myapp

COPY ./start.sh ./start.sh


RUN chmod +x ./*

# Viteで開発サーバーを起動する
COPY ./package.json /myapp


RUN apk update
RUN npm install -g @vue/cli
RUN npm install 
# RUN npm install vue-template-compiler


CMD ["npm", "run", "serve"]

# ENTRYPOINT [ "/frontend/start.sh" ]