version: "3.9"
services:
  db:
    image: mysql:8.0.26  
    platform: linux/x86_64
    volumes:
      - dev-prod-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      DB_DATABASE: tagmatch
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -e production"
    volumes:
      - .:/myapp
    environment:
      MYSQL_ROOT_PASSWORD: password
      DB_PORT: 3306
      DB_DATABASE: tagmatch
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  dev-prod-data:
    driver: local