version: "3.9"
services:
  db: #database.ymlのhostと同じにする必要がある
    build: 
      context: ./mysqldb-dockerfile
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
      DB_PORT: 3306
      DB_DATABASE: tagmatch
      DB_USERNAME: root
      DB_PASSWORD: 
      DB_HOST: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
 
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -e production"
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
    stdin_open: true
    tty: true

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
    stdin_open: true
    tty: true
      
volumes:
  mysql-data:
    driver: local
  public-data:
    driver: local
  tmp-data:
  log-data:
